apiVersion: apps/v1
kind: Deployment


metadata:
  name: pods


spec:
  selector:
    matchLabels:
      app: muhammad  
  replicas: 3
  template: 
    metadata:
      name: my-first-pod
      labels:
        app: muhammad
    spec:
      containers:
        - image: os2002/nginx-test
          name: nginx-container
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
          ports:
            - containerPort: 80